// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEstoque.Infra.Data.Contexts;

#nullable disable

namespace SistemaEstoque.Infra.Data.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEstoque.Domain.Entities.Entrada", b =>
                {
                    b.Property<Guid>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDENTRADA");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAHORA");

                    b.Property<Guid>("IdMercadoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDMERCADORIA");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("IdEntrada");

                    b.HasIndex("IdMercadoria");

                    b.ToTable("ENTRADA", (string)null);
                });

            modelBuilder.Entity("SistemaEstoque.Domain.Entities.Mercadoria", b =>
                {
                    b.Property<Guid>("IdMercadoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDMERCADORIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FABRICANTE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REGISTRO");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.HasKey("IdMercadoria");

                    b.ToTable("MERCADORIA", (string)null);
                });

            modelBuilder.Entity("SistemaEstoque.Domain.Entities.Saida", b =>
                {
                    b.Property<Guid>("IdSaida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSAIDA");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime")
                        .HasColumnName("DATAHORA");

                    b.Property<Guid>("IdMercadoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDMERCADORIA");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("IdSaida");

                    b.HasIndex("IdMercadoria");

                    b.ToTable("SAIDA", (string)null);
                });

            modelBuilder.Entity("SistemaEstoque.Domain.Entities.Entrada", b =>
                {
                    b.HasOne("SistemaEstoque.Domain.Entities.Mercadoria", "Mercadoria")
                        .WithMany("Entradas")
                        .HasForeignKey("IdMercadoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mercadoria");
                });

            modelBuilder.Entity("SistemaEstoque.Domain.Entities.Saida", b =>
                {
                    b.HasOne("SistemaEstoque.Domain.Entities.Mercadoria", "Mercadoria")
                        .WithMany("Saidas")
                        .HasForeignKey("IdMercadoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mercadoria");
                });

            modelBuilder.Entity("SistemaEstoque.Domain.Entities.Mercadoria", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Saidas");
                });
#pragma warning restore 612, 618
        }
    }
}
